FROM node:18-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

COPY tsconfig.json ./
COPY src/ ./src/
COPY tests/ ./tests/
COPY jest.config.js ./

# Папка для логов
RUN mkdir -p /app/logs

# Папка для отчетов о покрытии
RUN mkdir -p /app/coverage

CMD ["pnpm", "test"] 