FROM node:18-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

COPY tsconfig.json ./
COPY src/ ./src/

# Папка для логов
RUN mkdir -p /app/logs

# Установка nodemon для автоматической перезагрузки
RUN pnpm add -D nodemon

EXPOSE 3001

CMD ["pnpm", "dev"]