FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Создаем директорию для логов с правильными правами
RUN mkdir -p /tmp/logs

# Не переключаемся на пользователя node
# USER node

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]