version: '3.8'

services:
  # Тестовая база данных PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: neuro-blogger-test-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Сервис для тестирования
  neuro-blogger-telegram-bot-test:
    container_name: neuro-blogger-telegram-bot-test
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - LOG_DIR=/tmp/logs
    volumes:
      - ./logs:/tmp/logs
    ports:
      - "2999:2999"
      - "3008:3008"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3008/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  test-logs: 