FROM node:20-alpine

WORKDIR /app

# Установка зависимостей для сборки
RUN apk add --no-cache python3 make g++ git

# Установка pnpm и concurrently
RUN npm install -g pnpm concurrently

# Копирование файлов проекта
COPY package.json pnpm-lock.yaml ./
COPY . .

# Установка зависимостей и сборка
RUN pnpm install
RUN pnpm build

# Команда для запуска тестов с concurrently
CMD ["concurrently", "\"pnpm run bots\"", "\"pnpm run dev:inngest\""]