version: '3.8'

services:
  # Тестовая база данных PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: nb-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Сервис для тестирования
  neuro-blogger-telegram-bot-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: neuro-blogger-telegram-bot-test
    command: ["npm", "run", "test:payment-processor"]  # Автоматически запускать тесты платежной системы
    environment:
      - NODE_ENV=test
      - LOG_DIR=/app/logs
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - SUPABASE_URL=https://example.com
      - SUPABASE_SERVICE_KEY=example_key
      - PAYMENT_TEST_MODE=true
      - ENABLE_TEST_MODE=true
      - TEST_RETRY_COUNT=3
      - TEST_TIMEOUT=10000
      - PAYMENT_SERVICE_URL=http://localhost:3008
      - INNGEST_DEV_MODE=true
      - INNGEST_EVENT_KEY=test_event_key
    volumes:
      - test-logs:/app/logs
    ports:
      - 2999:2999
      - 3008:3008
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:2999/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  test-logs: 