FROM node:20-alpine

# Install pnpm globally
RUN npm install -g pnpm

WORKDIR /app

COPY package*.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install

# Создаем директорию для логов с правильными правами
RUN mkdir -p /tmp/logs && \
    chown -R node:node /tmp/logs

USER node

COPY --chown=node:node . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]