services:
  time:
    image: mcp/time
    environment:
      - MCP_MODE=stdio
      - TZ=UTC
    restart: unless-stopped

  docker:
    image: mcp/docker
    environment:
      - MCP_MODE=stdio
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PLATFORM=Darwin
      - HOST_DIR=/workspace
      - PROMPTS=[]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    command: ["--platform", "Darwin", "--prompts-file", "/workspace/prompts/prompts.md", "--host-dir", "/workspace"]
    restart: unless-stopped

networks:
  app-network:
    driver: bridge