---
- name: Configure Nginx Server
  hosts: elestio_server # Имя группы хостов (зададим в inventory)
  become: yes # Выполнять с sudo
  roles:
    - nginx # Указываем использовать роль из папки roles/nginx

# ansible-playbook playbook.yml --vault-password-file Users/playra/vault_password.txt