packages:
  # все пакеты в директориях, начинающихся с 'packages/'
  - 'packages/*'
  # все пакеты в поддиректориях
  - '**'
  # исключаем тестовые директории
  - '!**/test/**'
  - '!**/tests/**'
  - '!**/dist/**'
  - '!**/node_modules/**' 