[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.args]
SKIP_TYPE_CHECK = "true"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
numReplicas = 1

[service]
name = "999-multibots-telegraf"
