// Этот файл больше не нужен для определения базовых цен и констант.
// Оставляем только хелперы для сообщений.

import { MyContext } from '@/interfaces'
import { Markup } from 'telegraf'
import { logger } from '@/utils/logger'

/**
 * Отправляет сообщение о недостаточном количестве звезд.
 */
export async function sendInsufficientStarsMessage(
  ctx: MyContext,
  balance: number,
  isRu: boolean
): Promise<void> {
  // ... (код функции остается)
}

/**
 * Отправляет сообщение с текущим балансом и стоимостью операции.
 */
export async function sendBalanceMessage(
  ctx: MyContext,
  balance: number,
  cost: number,
  isRu: boolean,
  botUsername?: string
): Promise<void> {
  // ... (код функции остается)
}

// --- УДАЛЕНО ---
// export const starCost = ...
// export const interestRate = ...
// export const SYSTEM_CONFIG = ...
// export const conversionRates = ...
// export const conversionRatesV2 = ...
// export function calculateCostInStars(...) ...
// export function calculateCostInDollars(...) ...
// export function calculateCostInRubles(...) ...
// export const stepOptions = ...
// export const costDetails = ...
// export interface CostDetails ...
// export function calculateCost(...) ...
// function calculateFinalStarCostFromDollars(...) ...
// export const BASE_COSTS = ...
// export type CostValue = ...
// export function calculateModeCost(...) ...
// export const modeCosts = ...
// export const minCost = ...
// export const maxCost = ...
// export function getCostValue(...) ...
