export type BotType =
  | 'NEUROPHOTO'
  | 'NEUROBASE'
  | 'NEUROBLOGGER'
  | 'NEUROTESTER'

export const BOT_TYPES = {
  NEUROPHOTO: 'NEUROPHOTO',
  NEUROBASE: 'NEUROBASE',
  NEUROBLOGGER: 'NEUROBLOGGER',
  NEUROTESTER: 'NEUROTESTER',
} as const
