/**
 * @999-agents/plugin-neurophoto - Generate Image Action
 * ElizaOS Action for AI image generation
 */

import {
  Action,
  IAgentRuntime,
  Memory,
  State,
  HandlerCallback,
  ActionExample,
} from '@elizaos/core';
import { ReplicateService } from '../services/replicateService.js';
import type { GenerateImageOptions } from '../types/index.js';

export const generateImageAction: Action = {
  name: 'GENERATE_NEUROPHOTO',
  similes: [
    'MAKE_IMAGE',
    'CREATE_PHOTO',
    'NEUROPHOTO',
    'GENERATE_IMAGE',
    'AI_IMAGE',
    'DRAW_IMAGE',
  ],
  description: 'Генерирует AI-изображение с помощью Replicate и отправляет пользователю',

  /**
   * Validate if this action should run
   */
  validate: async (runtime: IAgentRuntime, message: Memory): Promise<boolean> => {
    const text = message.content?.text?.toLowerCase();

    if (!text) return false;

    // Check for trigger keywords
    const triggers = [
      'нейрофото',
      'neurophoto',
      '/generate',
      '/neurophoto',
      'создай изображение',
      'сгенерируй картинку',
      'нарисуй',
      'generate image',
      'create image',
      'draw',
    ];

    return triggers.some((trigger) => text.includes(trigger));
  },

  /**
   * Main handler for image generation
   */
  handler: async (
    runtime: IAgentRuntime,
    message: Memory,
    state: State | undefined,
    options,
    callback?: HandlerCallback
  ) => {
    try {
      console.log('🎨 [NEUROPHOTO] Starting image generation...');

      // Extract prompt from message
      const text = message.content?.text;

      if (!text) {
        console.error('❌ [NEUROPHOTO] No text in message');
        await callback?.({
          text: '❌ Не удалось получить текст сообщения.',
        });
        return {
          success: false,
          error: new Error('No text in message'),
        };
      }
      let prompt = text
        .replace(/\/neurophoto/gi, '')
        .replace(/\/generate/gi, '')
        .replace(/нейрофото/gi, '')
        .replace(/создай изображение/gi, '')
        .replace(/сгенерируй картинку/gi, '')
        .replace(/нарисуй/gi, '')
        .replace(/generate image/gi, '')
        .replace(/create image/gi, '')
        .replace(/draw/gi, '')
        .trim();

      // Validate prompt
      if (!prompt || prompt.length < 3) {
        console.log('❌ [NEUROPHOTO] Prompt too short');

        await callback?.({
          text: `❌ Пожалуйста, опишите какое изображение вы хотите создать.

**Примеры**:
• /neurophoto красивый закат над океаном
• /neurophoto футуристический город с летающими машинами
• /neurophoto портрет кота в космическом шлеме

Минимальная длина описания: 3 символа.`,
        });

        return {
          success: false,
          error: new Error('Промпт слишком короткий'),
        };
      }

      console.log(`📝 [NEUROPHOTO] Prompt: ${prompt}`);

      // Get Replicate service
      const replicateService =
        runtime.getService<ReplicateService>('replicate');

      if (!replicateService) {
        console.error('❌ [NEUROPHOTO] Replicate service not found');

        await callback?.({
          text: '❌ Сервис генерации изображений недоступен. Проверьте настройки REPLICATE_API_KEY.',
        });

        return {
          success: false,
          error: new Error('Replicate service not available'),
        };
      }

      // Send "generating" message
      await callback?.({
        text: '🎨 Генерирую изображение, это займёт 10-30 секунд...',
      });

      // Prepare generation options
      const genOptions: GenerateImageOptions = {
        prompt,
        numImages: 1,
        aspectRatio: '1:1',
      };

      // Generate image
      const result = await replicateService.generateImage(genOptions);

      if (!result.success || !result.imageUrls || result.imageUrls.length === 0) {
        console.error('❌ [NEUROPHOTO] Generation failed:', result.error);

        await callback?.({
          text: `❌ Не удалось сгенерировать изображение.

Ошибка: ${result.error || 'Неизвестная ошибка'}

Попробуйте:
• Упростить описание
• Использовать английский язык
• Попробовать позже`,
        });

        return {
          success: false,
          error: new Error(result.error || 'Generation failed'),
        };
      }

      console.log(`✅ [NEUROPHOTO] Generated ${result.imageUrls.length} images`);
      console.log(`⏱️  [NEUROPHOTO] Time: ${result.metadata?.generationTime}ms`);

      // Send result with image
      await callback?.({
        text: `✅ Изображение готово!

📝 **Промпт**: ${prompt}
🤖 **Модель**: ${result.metadata?.model}
⏱️ **Время генерации**: ${Math.round((result.metadata?.generationTime || 0) / 1000)}с`,
        attachments: result.imageUrls.map((url, index) => ({
          id: `neurophoto-${Date.now()}-${index}`,
          url,
          type: 'image',
          title: prompt,
          description: `Generated by ${result.metadata?.model}`,
        })),
      });

      return {
        success: true,
        text: 'Изображение успешно сгенерировано',
        data: {
          imageUrls: result.imageUrls,
          prompt,
          model: result.metadata?.model,
          generationTime: result.metadata?.generationTime,
        },
      };
    } catch (error) {
      console.error('❌ [NEUROPHOTO] Unexpected error:', error);

      await callback?.({
        text: '❌ Произошла непредвиденная ошибка при генерации изображения. Попробуйте позже или обратитесь к администратору.',
      });

      return {
        success: false,
        error: error instanceof Error ? error : new Error(String(error)),
      };
    }
  },

  /**
   * Example conversations for training
   */
  examples: [
    [
      {
        name: 'user',
        content: { text: '/neurophoto красивый закат над океаном' },
      },
      {
        name: 'assistant',
        content: {
          text: '✅ Изображение готово!\n\n📝 **Промпт**: красивый закат над океаном\n🤖 **Модель**: black-forest-labs/flux-schnell\n⏱️ **Время генерации**: 15с',
          action: 'GENERATE_NEUROPHOTO',
        },
      },
    ],
    [
      {
        name: 'user',
        content: { text: 'создай изображение футуристического города' },
      },
      {
        name: 'assistant',
        content: {
          text: '🎨 Генерирую изображение, это займёт 10-30 секунд...',
          action: 'GENERATE_NEUROPHOTO',
        },
      },
    ],
    [
      {
        name: 'user',
        content: { text: 'нарисуй кота в космическом шлеме' },
      },
      {
        name: 'assistant',
        content: {
          text: '✅ Изображение готово!\n\n📝 **Промпт**: кота в космическом шлеме',
          action: 'GENERATE_NEUROPHOTO',
        },
      },
    ],
  ] as ActionExample[][],
};
