-- =====================================================================
-- Лента сообщества: public_templates + template_likes
--
-- ПОЧЕМУ ЭТО ЗДЕСЬ, А НЕ В МИГРАЦИИ. Этих таблиц не существует НИГДЕ —
-- проверено по OpenAPI-схеме Supabase: обе отсутствуют. То есть лента не
-- сломалась при переносе, она не работала никогда: render-server.ts с самого
-- начала обращался к схеме, которую спроектировали, но не создали. В проде это
-- давало `relation "public_templates" does not exist` и «Failed to fetch feed»
-- на главном экране мини-аппа.
--
-- Схема выведена из кода-потребителя, а не придумана:
--   INSERT ... INTO public_templates (render-server.ts:2980) даёт список колонок,
--   типы ($9::jsonb, $10::jsonb, $11::jsonb) и значения по умолчанию,
--   SELECT в /api/feed даёт остальные читаемые поля,
--   LEFT JOIN template_likes ... AND tl.action = 'like' даёт форму лайков.
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public_templates (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- telegram_id везде в этой базе text, а не bigint: код передаёт
  -- String(data.telegram_id), и в users колонка тоже text. Расхождение типов
  -- здесь молча ломало бы JOIN'ы с users.
  telegram_id          text NOT NULL,

  creator_name         text NOT NULL DEFAULT 'Anonymous',
  creator_avatar       text,
  creator_username     text,

  name                 text NOT NULL DEFAULT 'Untitled',
  description          text,
  thumbnail_url        text,
  video_url            text NOT NULL,

  -- Приходят как ::jsonb из кода публикации.
  template_settings    jsonb NOT NULL DEFAULT '{}'::jsonb,
  assets               jsonb NOT NULL DEFAULT '[]'::jsonb,
  tracks               jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- Реміксы: откуда взят шаблон и кто автор исходника.
  parent_template_id   bigint REFERENCES public_templates(id) ON DELETE SET NULL,
  original_creator_id  text,

  is_public            boolean NOT NULL DEFAULT TRUE,
  is_featured          boolean NOT NULL DEFAULT FALSE,

  likes_count          integer NOT NULL DEFAULT 0,
  views_count          integer NOT NULL DEFAULT 0,
  uses_count           integer NOT NULL DEFAULT 0,

  created_at           timestamptz NOT NULL DEFAULT now(),
  -- Мягкое удаление: запрос ленты фильтрует по `deleted_at IS NULL`.
  deleted_at           timestamptz
);

-- Ровно те предикаты, по которым ходит /api/feed.
CREATE INDEX IF NOT EXISTS public_templates_feed_idx
  ON public_templates (created_at DESC)
  WHERE is_public AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS public_templates_popular_idx
  ON public_templates (likes_count DESC)
  WHERE is_public AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS public_templates_author_idx
  ON public_templates (telegram_id);

CREATE TABLE IF NOT EXISTS template_likes (
  template_id  bigint NOT NULL REFERENCES public_templates(id) ON DELETE CASCADE,
  telegram_id  text   NOT NULL,

  -- Код джойнит по `tl.action = 'like'`, значит поле хранит и обратное
  -- действие. Список закрыт, чтобы опечатка не создала третий вид молча.
  action       text   NOT NULL DEFAULT 'like'
               CHECK (action IN ('like', 'unlike')),

  created_at   timestamptz NOT NULL DEFAULT now(),

  -- Один голос на пользователя: без этого повторный тап накручивал бы счётчик.
  PRIMARY KEY (template_id, telegram_id)
);

CREATE INDEX IF NOT EXISTS template_likes_user_idx
  ON template_likes (telegram_id);

GRANT ALL ON public_templates, template_likes TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

COMMIT;
