export enum ModeEnum {
  MainMenu = 'main_menu',
  TextToImage = 'text_to_image',
  ImageToVideo = 'image_to_video',
  TextToVideo = 'text_to_video',
  TextToSpeech = 'text_to_speech',
  Voice = 'voice',
  Avatar = 'avatar',
  ChatWithAvatar = 'chat_with_avatar',
  SelectModelWizard = 'select_model_wizard',
  NeuroPhoto = 'neurophoto',
  NeuroPhotoV2 = 'neurophoto_v2',
  ImageToPrompt = 'image_to_prompt',
  DigitalAvatarBody = 'digital_avatar_body',
  DigitalAvatarBodyV2 = 'digital_avatar_body_v2',
  TopUpBalance = 'top_up_balance',
  Balance = 'balance',
  Help = 'help',
  Invite = 'invite',
  Tech = 'tech',
  Stats = 'stats',
  Price = 'price',
}
