/**
 * Себестоимость моделей KieAI, $ — СГЕНЕРИРОВАНО.
 *
 * НЕ ПРАВИТЬ РУКАМИ: правка исчезнет при следующем запуске
 * `scripts/gen-kie-swift.ts`. Источник — прайс KieAI (POST
 * model-pricing/page), тот же проход, что собирает Swift-каталог.
 *
 * Значение — САМЫЙ ДЕШЁВЫЙ вариант модели (у одной модели бывает восемь цен
 * на разные разрешения), поэтому в интерфейсе оно показано со словом «от».
 * `null` — провайдер цены не назвал; такую модель к оплате не допускаем:
 * назвать сумму до нажатия мы не сможем.
 */
export const СЕБЕСТОИМОСТЬ_USD: Record<string, number | null> = {
  'seedream/5-lite-text-to-image': 0.0275,
  'seedream/5-pro-text-to-image': 0.0025,
  'seedream/5-pro-image-to-image': 0.0025,
  'google/imagen4-fast': 0.02,
  'google/imagen4-ultra': 0.02,
  'google/imagen4': 0.02,
  'google/nano-banana-edit': 0.02,
  'google/nano-banana': 0.02,
  'grok-imagine/text-to-image': 0.02,
  'grok-imagine/image-to-image': 0.02,
  'topaz/image-upscale': 0.05,
  'recraft/remove-background': 0.005,
  'recraft/crisp-upscale': 0.0025,
  'ideogram/v3-text-to-image': 0.0175,
  'ideogram/character': 0.06,
  'qwen/text-to-image': 0.02,
  'qwen/image-edit': 0.03,
  'qwen3/text-to-image': 0.0025,
  'wan/2-7-image': 0.024,
  'grok-imagine/text-to-video': 0.012,
  'grok-imagine/image-to-video': 0.012,
  'kling/ai-avatar-standard': 0.04,
  'kling/v2-1-pro': 0.125,
  'kling/v3-turbo-text-to-video': 0.09,
  'bytedance/seedance-2': 0.057,
  'bytedance/seedance-2-fast': 0.034,
  'bytedance/v1-pro-text-to-video': 0.00875,
  'hailuo/02-text-to-video-pro': 0.06,
  'wan/2-5-text-to-video': 0.3,
  'wan/2-6-text-to-video': 0.35,
  'wan/3-0-video': 0.04,
  'topaz/video-upscale': 0.04,
  'infinitalk/from-audio': 0.015,
  'minimax-h3/text-to-video': 0.02,
  'omnihuman-1-5': 0.135,
  'volcengine/video-to-video-lip-sync': 0.04,
  'elevenlabs/audio-isolation': 0.07,
  'elevenlabs/text-to-speech-multilingual-v2': 0.03,
  'elevenlabs/text-to-speech-turbo-2-5': 0.03,
  'google/gemini-3-1-flash-tts': 0.7,
  'sora-2-text-to-video': null,
  'sora-2-pro-text-to-video': null,
  'sora-2-image-to-video': null,
  'veed/fabric-1': null,
  'gpt-5-2': 0.44,
  'gemini-3-pro': 0.5,
  'gemini-2.5-flash': 0.09,
  'glm-5.3': null,
}

/** Единица измерения цены: «за секунду», «за картинку» и т. п. */
export const ЕДИНИЦА_ЦЕНЫ: Record<string, string | null> = {
  'seedream/5-lite-text-to-image': 'за картинку',
  'seedream/5-pro-text-to-image': 'за картинку',
  'seedream/5-pro-image-to-image': 'за картинку',
  'google/imagen4-fast': 'за запрос',
  'google/imagen4-ultra': 'за запрос',
  'google/imagen4': 'за запрос',
  'google/nano-banana-edit': 'за картинку',
  'google/nano-banana': 'за картинку',
  'grok-imagine/text-to-image': 'за картинку',
  'grok-imagine/image-to-image': 'за картинку',
  'topaz/image-upscale': 'за картинку',
  'recraft/remove-background': 'за картинку',
  'recraft/crisp-upscale': 'за картинку',
  'ideogram/v3-text-to-image': 'за картинку',
  'ideogram/character': 'за картинку',
  'qwen/text-to-image': 'за мегапиксель',
  'qwen/image-edit': 'за мегапиксель',
  'qwen3/text-to-image': 'за картинку',
  'wan/2-7-image': 'за картинку',
  'grok-imagine/text-to-video': 'за секунду',
  'grok-imagine/image-to-video': 'за секунду',
  'kling/ai-avatar-standard': 'за секунду',
  'kling/v2-1-pro': 'за ролик',
  'kling/v3-turbo-text-to-video': 'за секунду',
  'bytedance/seedance-2': 'за секунду',
  'bytedance/seedance-2-fast': 'за секунду',
  'bytedance/v1-pro-text-to-video': 'за секунду',
  'hailuo/02-text-to-video-pro': 'за ролик',
  'wan/2-5-text-to-video': 'за ролик',
  'wan/2-6-text-to-video': 'за ролик',
  'wan/3-0-video': 'за секунду',
  'topaz/video-upscale': 'за секунду',
  'infinitalk/from-audio': 'за секунду',
  'minimax-h3/text-to-video': 'за картинку',
  'omnihuman-1-5': 'за секунду',
  'volcengine/video-to-video-lip-sync': 'за секунду',
  'elevenlabs/audio-isolation': 'за 1000 знаков',
  'elevenlabs/text-to-speech-multilingual-v2': 'за 1000 знаков',
  'elevenlabs/text-to-speech-turbo-2-5': 'за 1000 знаков',
  'google/gemini-3-1-flash-tts': 'за млн токенов',
  'sora-2-text-to-video': null,
  'sora-2-pro-text-to-video': null,
  'sora-2-image-to-video': null,
  'veed/fabric-1': null,
  'gpt-5-2': 'за млн токенов',
  'gemini-3-pro': 'за млн токенов',
  'gemini-2.5-flash': 'за млн токенов',
  'glm-5.3': null,
}
