import { Scenes } from 'telegraf'
import { MyContext } from './interfaces'
import {
  startScene,
  subscriptionScene,
  subscriptionCheckScene,
  createUserScene,
  checkBalanceScene,
  chatWithAvatarWizard,
  menuScene,
  getEmailWizard,
  getRuBillWizard,
  balanceScene,
  avatarBrainWizard,
  imageToPromptWizard,
  textToImageWizard,
  improvePromptWizard,
  sizeWizard,
  neuroPhotoWizard,
  neuroPhotoWizardV2,
  textToVideoWizard,
  imageToVideoWizard,
  cancelPredictionsWizard,
  trainFluxModelWizard,
  uploadTrainFluxModelScene,
  digitalAvatarBodyWizard,
  digitalAvatarBodyWizardV2,
  selectAiTextModel,
  voiceAvatarWizard,
  textToSpeechWizard,
  paymentScene,
  neuroCoderScene,
  lipSyncWizard,
  helpScene,
  inviteScene,
  selectModelScene,
  selectNeuroPhotoScene,
  broadcastWizard,
  levelQuestWizard,
  uploadVideoScene,
} from './scenes'
import { ModeEnum } from './price/types/modes'

export const stage = new Scenes.Stage<MyContext>(
  [
    startScene,
    subscriptionScene,
    subscriptionCheckScene,
    createUserScene,
    checkBalanceScene,
    chatWithAvatarWizard,
    menuScene,
    getEmailWizard,
    getRuBillWizard,
    balanceScene,
    avatarBrainWizard,
    imageToPromptWizard,
    textToImageWizard,
    improvePromptWizard,
    sizeWizard,
    neuroPhotoWizard,
    neuroPhotoWizardV2,
    textToVideoWizard,
    imageToVideoWizard,
    cancelPredictionsWizard,
    trainFluxModelWizard,
    uploadTrainFluxModelScene,
    digitalAvatarBodyWizard,
    digitalAvatarBodyWizardV2,
    selectAiTextModel,
    voiceAvatarWizard,
    textToSpeechWizard,
    paymentScene,
    neuroCoderScene,
    lipSyncWizard,
    helpScene,
    inviteScene,
    selectModelScene,
    selectNeuroPhotoScene,
    broadcastWizard,
    ...levelQuestWizard,
    uploadVideoScene,
  ],

  {
    // Опциональные параметры:
    ttl: 3600, // Время жизни данных сцены (в секундах)
    default: ModeEnum.StartScene, // Дефолтная сцена при ошибках
  }
)
