#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Получаем текущую и удаленную ветку, а также ref
current_branch=$(git rev-parse --abbrev-ref HEAD)
remote_branch=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null | sed 's#^.*/##') # Получаем имя удаленной ветки

# Проверяем, является ли целевая ветка 'main'
if [ "$remote_branch" = "main" ]; then
  echo "🧘‍♂️ Обнаружена попытка push в 'main'. Запуск проверки типов TypeScript (tsc --noEmit)..."
  pnpm exec tsc --noEmit
  exit_code=$?

  if [ $exit_code -ne 0 ]; then
    echo "❌ Ошибка: Проверка типов TypeScript не пройдена. Push в 'main' отменен."
    echo "🕉️ Пожалуйста, исправьте ошибки типов перед повторной попыткой."
    exit 1
  else
    echo "✅ Проверка типов TypeScript успешно пройдена для ветки 'main'."
  fi
else
  echo "push не в 'main' ($remote_branch), проверка типов пропускается хуком pre-push."
fi

exit 0 