name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Или актуальная LTS версия Node.js

    - name: Setup PNPM
      uses: pnpm/action-setup@v3
      with:
        version: 8 # Или актуальная версия pnpm
        run_install: false # Мы установим зависимости позже вручную

    - name: Get pnpm store directory
      id: get-pnpm-store-directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.get-pnpm-store-directory.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Run type check
      run: pnpm typecheck

    - name: Run linter
      run: pnpm lint

    - name: Run tests
      run: pnpm vitest run 